### ISSUE TITLE
can not find test folder?

### ISSUE THREAD

**Issue by nevermore0127** [lixiny/Handeye-Calibration-ROS#1]
-- Configuring done
CMake Error at handeye_calib_sphere/CMakeLists.txt:150 (add_executable):
  Cannot find source file:

    test/generate_fake_data_v2.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at handeye_calib_sphere/CMakeLists.txt:139 (add_executable):
  Cannot find source file:

    test/generate_fake_data.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at handeye_calib_sphere/CMakeLists.txt:160 (add_executable):
  Cannot find source file:

    test/generate_fake_data_v3.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at handeye_calib_sphere/CMakeLists.txt:171 (add_executable):
  Cannot find source file:

    test/fit_sphere.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at handeye_calib_sphere/CMakeLists.txt:150 (add_executable):
  No SOURCES given to target: generate_fake_data_v2

CMake Error at handeye_calib_sphere/CMakeLists.txt:139 (add_executable):
  No SOURCES given to target: generate_fake_data

CMake Error at handeye_calib_sphere/CMakeLists.txt:160 (add_executable):
  No SOURCES given to target: generate_fake_data_v3

CMake Error at handeye_calib_sphere/CMakeLists.txt:171 (add_executable):
  No SOURCES given to target: fit_sphere

-- Build files have been written to: /home/long/Handeye_ros_ws/Handeye-Calibration-ROS/build

**Comment by lixiny** [comment]
those test files are not included in this repo. I forgot to remove them in CMakeLists  
deleting those lines in CMakeList.txt would help you, I wish.
